name: Playwright

on:
  workflow_call:

jobs:
  e2e:
    name: Playwright - ${{ matrix.dataTarget }}
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        dataTarget:
          - en
          - de

    env:
      dataTarget: ${{ matrix.dataTarget }}
      VENDURE_SHOP_API_URL: http://localhost:3000/shop-api
      NEXT_PUBLIC_VENDURE_SHOP_API_URL: http://localhost:3000/shop-api
      SUPERADMIN_USERNAME: superadmin
      SUPERADMIN_PASSWORD: superadmin
      COOKIE_SECRET: test-cookie-secret